consignment:
  boxes:
    min: 10
    max: 10
  items_per_box:
    default: 200
    air:
      default: 200
    maritime:
      default: 200
  origins:
    - Netherlands
    - Mexico
    - Israel
    - Japan
    - New Zealand
    - India
    - Tanzania
  flowers:
    - Hyacinthus
    - Rosa
    - Gerbera
    - Agapanthus
    - Aegilops
    - Protea
    - Liatris
    - Mokara
    - Anemone
    - Actinidia
  ports:
    - NY JFK CBP
    - FL Miami Air CBP
    - HI Honolulu CBP
    - AZ Phoenix CBP
    - VA Dulles CBP
    - CA San Francisco CBP
    - WA Seattle Air CBP
    - TX Brownsville CBP
    - WA Blaine CBP
contamination:
  contamination_unit: item
  contamination_rate:
    distribution: beta
    value: 0.01
    parameters:
      - 0.243875716307
      - 223.427186223
  arrangement: clustered
  clustered:
    contaminated_units_per_cluster: 25
    distribution: continuous
    random:
      cluster_item_width: 100
  random_box:
    probability: 0.2
    ratio: 0.5
release_programs:
  naive_cfrp:
    flowers:
      - Hyacinthus
      - Gerbera
      - Rosa
      - Actinidia
    max_boxes: 10 # do not apply to consignments larger than
inspection:
  unit: item
  within_box_proportion: 0.05
  sample_strategy: hypergeometric
  min_boxes: 0
  tolerance_level: 0
  proportion:
    value: 0.02
  hypergeometric:
    detection_level: 0.1
    confidence_level: 0.95
  fixed_n: 10
  selection_strategy: random
  cluster:
    cluster_selection: cluster
    interval: 5
